spring.application.name=itau-balance-api
#logging.level.itau_balance_api=DEBUG

#AWS
aws.sqs.queue-name=transacoes-financeiras-processadas
aws.access=test
aws.secret=test
aws.region=sa-east-1
aws.endpoint=http://localhost:4566